version: 1
labels:
- label: "feature"
  title: "((E|e)nhance|(a|A)dd|(u|U)pdate)"
- label: "bug"
  title: :"((B|b)ug|(F|f)ix)"
- label: "minor"
  size-above: 1
  size-below: 100
- label: "major"
  size-above: 100
