tag-template: '$NEXT_MINOR_VERSION'
name-template: '$NEXT_MINOR_VERSION'
categories:
  - title: "🚀 Features and Enhancements"
    labels:
      - "feature"

  - title: "🐛 Bug Fixes"
    labels:
      - "bug"

template: |
  ## What’s Changed
  $CHANGES
