categories:
  - title: "🚀 Features and Enhancements"
    labels:
      - "feature"
      - "enhancement"
      - "add"
      - "adding"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
template: |
  ## What’s Changed
  $CHANGES