name: Update Changelog

on:
  release:
    types: [published]

jobs:
  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update CHANGELOG.md for new release.
          file_pattern: CHANGELOG.md
