name: Run Python Script

on: [ push ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      # - name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt

      - name: Run script
        run: |
          python3 scripts/hello.py
